inherit_from: .rubocop_todo.yml

Encoding:
  Enabled: false

Metrics/ClassLength:
  CountComments: false

AllCops:
  Exclude:
    - contentful-management.gemspec
    - bin/cma-console
    - spec/**/*
    - examples/**/*
    - Guardfile
    - Gemfile
    - Rakefile

Metrics/LineLength:
  Max: 135

Metrics/ClassLength:
  Max: 350

Metrics/ModuleLength:
  Max: 350

Style/SignalException:
  EnforcedStyle: 'semantic'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Name/MemoizedInstanceVariableName:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineWhenThen:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false
